# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\code\空压机\AirCompressorUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(387, 539)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setObjectName("start")
        self.gridLayout_2.addWidget(self.start, 6, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.setRack = QtWidgets.QLineEdit(self.centralwidget)
        self.setRack.setObjectName("setRack")
        self.horizontalLayout_3.addWidget(self.setRack)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.connectPLC = QtWidgets.QPushButton(self.centralwidget)
        self.connectPLC.setObjectName("connectPLC")
        self.gridLayout_2.addWidget(self.connectPLC, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.IPaddress = QtWidgets.QLineEdit(self.centralwidget)
        self.IPaddress.setPlaceholderText("")
        self.IPaddress.setObjectName("IPaddress")
        self.horizontalLayout_2.addWidget(self.IPaddress)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.setSlot = QtWidgets.QLineEdit(self.centralwidget)
        self.setSlot.setObjectName("setSlot")
        self.horizontalLayout_4.addWidget(self.setSlot)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.disconnectPLC = QtWidgets.QPushButton(self.centralwidget)
        self.disconnectPLC.setObjectName("disconnectPLC")
        self.gridLayout_2.addWidget(self.disconnectPLC, 4, 0, 1, 1)
        self.IOtab = QtWidgets.QTabWidget(self.centralwidget)
        self.IOtab.setObjectName("IOtab")
        self.readPLC = QtWidgets.QWidget()
        self.readPLC.setObjectName("readPLC")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.readPLC)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.IOtab.addTab(self.readPLC, "")
        self.writePLC = QtWidgets.QWidget()
        self.writePLC.setObjectName("writePLC")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.writePLC)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.IOtab.addTab(self.writePLC, "")
        self.gridLayout_2.addWidget(self.IOtab, 5, 0, 1, 1)
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setObjectName("stop")
        self.gridLayout_2.addWidget(self.stop, 7, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.IOtab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "空压机控制软件"))
        self.start.setText(_translate("MainWindow", "开始读取"))
        self.label_3.setText(_translate("MainWindow", "设备卡号"))
        self.connectPLC.setText(_translate("MainWindow", "连接PLC"))
        self.label_2.setText(_translate("MainWindow", "设备IP  "))
        self.label_4.setText(_translate("MainWindow", "设备槽号"))
        self.disconnectPLC.setText(_translate("MainWindow", "断开PLC"))
        self.IOtab.setTabText(self.IOtab.indexOf(self.readPLC), _translate("MainWindow", "读取"))
        self.IOtab.setTabText(self.IOtab.indexOf(self.writePLC), _translate("MainWindow", "写入"))
        self.stop.setText(_translate("MainWindow", "停止读取"))
